/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AdmissionInquiry {
  'id' : string,
  'name' : string,
  'createdAt' : bigint,
  'isRead' : boolean,
  'email' : string,
  'message' : string,
  'classLevel' : ClassLevel,
  'mobile' : string,
}
export interface Batch {
  'id' : string,
  'fee' : bigint,
  'timing' : string,
  'isActive' : boolean,
  'totalSeats' : bigint,
  'availableSeats' : bigint,
  'schedule' : string,
  'className' : string,
  'batchName' : string,
  'startDate' : bigint,
}
export interface ClassContent {
  'id' : string,
  'url' : string,
  'title' : string,
  'contentType' : ContentType,
  'body' : string,
  'createdAt' : bigint,
  'description' : string,
  'classLevel' : ClassLevel,
}
export type ClassLevel = { 'Class1' : null } |
  { 'Class2' : null } |
  { 'Class3' : null } |
  { 'Class4' : null } |
  { 'Class5' : null } |
  { 'Class6' : null } |
  { 'Class7' : null } |
  { 'Class8' : null } |
  { 'Nursery' : null };
export type ContentType = { 'pdf' : null } |
  { 'video' : null } |
  { 'test' : null } |
  { 'message' : null } |
  { 'worksheet' : null };
export interface Faculty {
  'id' : string,
  'bio' : string,
  'subject' : string,
  'displayOrder' : bigint,
  'name' : string,
  'photoUrl' : string,
  'qualification' : string,
}
export interface GalleryItem {
  'id' : string,
  'title' : string,
  'imageUrl' : string,
  'caption' : string,
  'uploadedAt' : bigint,
}
export interface Stats {
  'facultyCount' : bigint,
  'contentCount' : bigint,
  'galleryCount' : bigint,
  'inquiryCount' : bigint,
  'batchCount' : bigint,
}
export interface UserProfile {
  'enrolledClasses' : Array<string>,
  'name' : string,
  'role' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addBatch' : ActorMethod<[Batch], undefined>,
  'addClassContent' : ActorMethod<[ClassContent], undefined>,
  'addFaculty' : ActorMethod<[Faculty], undefined>,
  'addGalleryItem' : ActorMethod<[GalleryItem], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'claimFirstAdmin' : ActorMethod<[], boolean>,
  'deleteBatch' : ActorMethod<[string], undefined>,
  'deleteClassContent' : ActorMethod<[string], undefined>,
  'deleteFaculty' : ActorMethod<[string], undefined>,
  'deleteGalleryItem' : ActorMethod<[string], undefined>,
  'getActiveBatches' : ActorMethod<[], Array<Batch>>,
  'getAllAdmissionInquiries' : ActorMethod<[], Array<AdmissionInquiry>>,
  'getAllBatches' : ActorMethod<[], Array<Batch>>,
  'getAllFaculty' : ActorMethod<[], Array<Faculty>>,
  'getAllGalleryItems' : ActorMethod<[], Array<GalleryItem>>,
  'getByClass' : ActorMethod<[ClassLevel], Array<ClassContent>>,
  'getByClassAndType' : ActorMethod<
    [ClassLevel, ContentType],
    Array<ClassContent>
  >,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getStats' : ActorMethod<[], Stats>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'markInquiryAsRead' : ActorMethod<[string], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'submitAdmissionInquiry' : ActorMethod<[AdmissionInquiry], undefined>,
  'updateBatch' : ActorMethod<[string, Batch], undefined>,
  'updateClassContent' : ActorMethod<[string, ClassContent], undefined>,
  'updateFaculty' : ActorMethod<[string, Faculty], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];