/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const Batch = IDL.Record({
  'id' : IDL.Text,
  'fee' : IDL.Nat,
  'timing' : IDL.Text,
  'isActive' : IDL.Bool,
  'totalSeats' : IDL.Nat,
  'availableSeats' : IDL.Nat,
  'schedule' : IDL.Text,
  'className' : IDL.Text,
  'batchName' : IDL.Text,
  'startDate' : IDL.Int,
});
export const ContentType = IDL.Variant({
  'pdf' : IDL.Null,
  'video' : IDL.Null,
  'test' : IDL.Null,
  'message' : IDL.Null,
  'worksheet' : IDL.Null,
});
export const ClassLevel = IDL.Variant({
  'Class1' : IDL.Null,
  'Class2' : IDL.Null,
  'Class3' : IDL.Null,
  'Class4' : IDL.Null,
  'Class5' : IDL.Null,
  'Class6' : IDL.Null,
  'Class7' : IDL.Null,
  'Class8' : IDL.Null,
  'Nursery' : IDL.Null,
});
export const ClassContent = IDL.Record({
  'id' : IDL.Text,
  'url' : IDL.Text,
  'title' : IDL.Text,
  'contentType' : ContentType,
  'body' : IDL.Text,
  'createdAt' : IDL.Int,
  'description' : IDL.Text,
  'classLevel' : ClassLevel,
});
export const Faculty = IDL.Record({
  'id' : IDL.Text,
  'bio' : IDL.Text,
  'subject' : IDL.Text,
  'displayOrder' : IDL.Nat,
  'name' : IDL.Text,
  'photoUrl' : IDL.Text,
  'qualification' : IDL.Text,
});
export const GalleryItem = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'imageUrl' : IDL.Text,
  'caption' : IDL.Text,
  'uploadedAt' : IDL.Int,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const AdmissionInquiry = IDL.Record({
  'id' : IDL.Text,
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
  'isRead' : IDL.Bool,
  'email' : IDL.Text,
  'message' : IDL.Text,
  'classLevel' : ClassLevel,
  'mobile' : IDL.Text,
});
export const UserProfile = IDL.Record({
  'enrolledClasses' : IDL.Vec(IDL.Text),
  'name' : IDL.Text,
  'role' : IDL.Text,
});
export const Stats = IDL.Record({
  'facultyCount' : IDL.Nat,
  'contentCount' : IDL.Nat,
  'galleryCount' : IDL.Nat,
  'inquiryCount' : IDL.Nat,
  'batchCount' : IDL.Nat,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addBatch' : IDL.Func([Batch], [], []),
  'addClassContent' : IDL.Func([ClassContent], [], []),
  'addFaculty' : IDL.Func([Faculty], [], []),
  'addGalleryItem' : IDL.Func([GalleryItem], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'claimFirstAdmin' : IDL.Func([], [IDL.Bool], []),
  'deleteBatch' : IDL.Func([IDL.Text], [], []),
  'deleteClassContent' : IDL.Func([IDL.Text], [], []),
  'deleteFaculty' : IDL.Func([IDL.Text], [], []),
  'deleteGalleryItem' : IDL.Func([IDL.Text], [], []),
  'getActiveBatches' : IDL.Func([], [IDL.Vec(Batch)], ['query']),
  'getAllAdmissionInquiries' : IDL.Func(
      [],
      [IDL.Vec(AdmissionInquiry)],
      ['query'],
    ),
  'getAllBatches' : IDL.Func([], [IDL.Vec(Batch)], ['query']),
  'getAllFaculty' : IDL.Func([], [IDL.Vec(Faculty)], ['query']),
  'getAllGalleryItems' : IDL.Func([], [IDL.Vec(GalleryItem)], ['query']),
  'getByClass' : IDL.Func([ClassLevel], [IDL.Vec(ClassContent)], ['query']),
  'getByClassAndType' : IDL.Func(
      [ClassLevel, ContentType],
      [IDL.Vec(ClassContent)],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getStats' : IDL.Func([], [Stats], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'markInquiryAsRead' : IDL.Func([IDL.Text], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'submitAdmissionInquiry' : IDL.Func([AdmissionInquiry], [], []),
  'updateBatch' : IDL.Func([IDL.Text, Batch], [], []),
  'updateClassContent' : IDL.Func([IDL.Text, ClassContent], [], []),
  'updateFaculty' : IDL.Func([IDL.Text, Faculty], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const Batch = IDL.Record({
    'id' : IDL.Text,
    'fee' : IDL.Nat,
    'timing' : IDL.Text,
    'isActive' : IDL.Bool,
    'totalSeats' : IDL.Nat,
    'availableSeats' : IDL.Nat,
    'schedule' : IDL.Text,
    'className' : IDL.Text,
    'batchName' : IDL.Text,
    'startDate' : IDL.Int,
  });
  const ContentType = IDL.Variant({
    'pdf' : IDL.Null,
    'video' : IDL.Null,
    'test' : IDL.Null,
    'message' : IDL.Null,
    'worksheet' : IDL.Null,
  });
  const ClassLevel = IDL.Variant({
    'Class1' : IDL.Null,
    'Class2' : IDL.Null,
    'Class3' : IDL.Null,
    'Class4' : IDL.Null,
    'Class5' : IDL.Null,
    'Class6' : IDL.Null,
    'Class7' : IDL.Null,
    'Class8' : IDL.Null,
    'Nursery' : IDL.Null,
  });
  const ClassContent = IDL.Record({
    'id' : IDL.Text,
    'url' : IDL.Text,
    'title' : IDL.Text,
    'contentType' : ContentType,
    'body' : IDL.Text,
    'createdAt' : IDL.Int,
    'description' : IDL.Text,
    'classLevel' : ClassLevel,
  });
  const Faculty = IDL.Record({
    'id' : IDL.Text,
    'bio' : IDL.Text,
    'subject' : IDL.Text,
    'displayOrder' : IDL.Nat,
    'name' : IDL.Text,
    'photoUrl' : IDL.Text,
    'qualification' : IDL.Text,
  });
  const GalleryItem = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'imageUrl' : IDL.Text,
    'caption' : IDL.Text,
    'uploadedAt' : IDL.Int,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const AdmissionInquiry = IDL.Record({
    'id' : IDL.Text,
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
    'isRead' : IDL.Bool,
    'email' : IDL.Text,
    'message' : IDL.Text,
    'classLevel' : ClassLevel,
    'mobile' : IDL.Text,
  });
  const UserProfile = IDL.Record({
    'enrolledClasses' : IDL.Vec(IDL.Text),
    'name' : IDL.Text,
    'role' : IDL.Text,
  });
  const Stats = IDL.Record({
    'facultyCount' : IDL.Nat,
    'contentCount' : IDL.Nat,
    'galleryCount' : IDL.Nat,
    'inquiryCount' : IDL.Nat,
    'batchCount' : IDL.Nat,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addBatch' : IDL.Func([Batch], [], []),
    'addClassContent' : IDL.Func([ClassContent], [], []),
    'addFaculty' : IDL.Func([Faculty], [], []),
    'addGalleryItem' : IDL.Func([GalleryItem], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'claimFirstAdmin' : IDL.Func([], [IDL.Bool], []),
    'deleteBatch' : IDL.Func([IDL.Text], [], []),
    'deleteClassContent' : IDL.Func([IDL.Text], [], []),
    'deleteFaculty' : IDL.Func([IDL.Text], [], []),
    'deleteGalleryItem' : IDL.Func([IDL.Text], [], []),
    'getActiveBatches' : IDL.Func([], [IDL.Vec(Batch)], ['query']),
    'getAllAdmissionInquiries' : IDL.Func(
        [],
        [IDL.Vec(AdmissionInquiry)],
        ['query'],
      ),
    'getAllBatches' : IDL.Func([], [IDL.Vec(Batch)], ['query']),
    'getAllFaculty' : IDL.Func([], [IDL.Vec(Faculty)], ['query']),
    'getAllGalleryItems' : IDL.Func([], [IDL.Vec(GalleryItem)], ['query']),
    'getByClass' : IDL.Func([ClassLevel], [IDL.Vec(ClassContent)], ['query']),
    'getByClassAndType' : IDL.Func(
        [ClassLevel, ContentType],
        [IDL.Vec(ClassContent)],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getStats' : IDL.Func([], [Stats], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'markInquiryAsRead' : IDL.Func([IDL.Text], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'submitAdmissionInquiry' : IDL.Func([AdmissionInquiry], [], []),
    'updateBatch' : IDL.Func([IDL.Text, Batch], [], []),
    'updateClassContent' : IDL.Func([IDL.Text, ClassContent], [], []),
    'updateFaculty' : IDL.Func([IDL.Text, Faculty], [], []),
  });
};

export const init = ({ IDL }) => { return []; };