/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Batch {
    id: string;
    fee: bigint;
    timing: string;
    isActive: boolean;
    totalSeats: bigint;
    availableSeats: bigint;
    schedule: string;
    className: string;
    batchName: string;
    startDate: bigint;
}
export interface ClassContent {
    id: string;
    url: string;
    title: string;
    contentType: ContentType;
    body: string;
    createdAt: bigint;
    description: string;
    classLevel: ClassLevel;
}
export interface AdmissionInquiry {
    id: string;
    name: string;
    createdAt: bigint;
    isRead: boolean;
    email: string;
    message: string;
    classLevel: ClassLevel;
    mobile: string;
}
export interface _CaffeineStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface Stats {
    facultyCount: bigint;
    contentCount: bigint;
    galleryCount: bigint;
    inquiryCount: bigint;
    batchCount: bigint;
}
export interface Faculty {
    id: string;
    bio: string;
    subject: string;
    displayOrder: bigint;
    name: string;
    photoUrl: string;
    qualification: string;
}
export interface _CaffeineStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface GalleryItem {
    id: string;
    title: string;
    imageUrl: string;
    caption: string;
    uploadedAt: bigint;
}
export interface UserProfile {
    enrolledClasses: Array<string>;
    name: string;
    role: string;
}
export interface _CaffeineStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export enum ClassLevel {
    Class1 = "Class1",
    Class2 = "Class2",
    Class3 = "Class3",
    Class4 = "Class4",
    Class5 = "Class5",
    Class6 = "Class6",
    Class7 = "Class7",
    Class8 = "Class8",
    Nursery = "Nursery"
}
export enum ContentType {
    pdf = "pdf",
    video = "video",
    test = "test",
    message = "message",
    worksheet = "worksheet"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _caffeineStorageBlobIsLive(hash: Uint8Array): Promise<boolean>;
    _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _caffeineStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _caffeineStorageCreateCertificate(blobHash: string): Promise<_CaffeineStorageCreateCertificateResult>;
    _caffeineStorageRefillCashier(refillInformation: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult>;
    _caffeineStorageUpdateGatewayPrincipals(): Promise<void>;
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addBatch(batch: Batch): Promise<void>;
    addClassContent(content: ClassContent): Promise<void>;
    addFaculty(facultyMember: Faculty): Promise<void>;
    addGalleryItem(item: GalleryItem): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    deleteBatch(id: string): Promise<void>;
    deleteClassContent(id: string): Promise<void>;
    deleteFaculty(id: string): Promise<void>;
    deleteGalleryItem(id: string): Promise<void>;
    getActiveBatches(): Promise<Array<Batch>>;
    getAllAdmissionInquiries(): Promise<Array<AdmissionInquiry>>;
    getAllBatches(): Promise<Array<Batch>>;
    getAllFaculty(): Promise<Array<Faculty>>;
    getAllGalleryItems(): Promise<Array<GalleryItem>>;
    getByClass(classLevel: ClassLevel): Promise<Array<ClassContent>>;
    getByClassAndType(classLevel: ClassLevel, contentType: ContentType): Promise<Array<ClassContent>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getStats(): Promise<Stats>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    markInquiryAsRead(id: string): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    submitAdmissionInquiry(inquiry: AdmissionInquiry): Promise<void>;
    updateBatch(id: string, updatedData: Batch): Promise<void>;
    updateClassContent(id: string, updatedData: ClassContent): Promise<void>;
    updateFaculty(id: string, updatedData: Faculty): Promise<void>;
}
import type { AdmissionInquiry as _AdmissionInquiry, ClassContent as _ClassContent, ClassLevel as _ClassLevel, ContentType as _ContentType, UserProfile as _UserProfile, UserRole as _UserRole, _CaffeineStorageRefillInformation as __CaffeineStorageRefillInformation, _CaffeineStorageRefillResult as __CaffeineStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _caffeineStorageBlobIsLive(arg0: Uint8Array): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobIsLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobIsLive(arg0);
            return result;
        }
    }
    async _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobsToDelete();
            return result;
        }
    }
    async _caffeineStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _caffeineStorageCreateCertificate(arg0: string): Promise<_CaffeineStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _caffeineStorageRefillCashier(arg0: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _caffeineStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addBatch(arg0: Batch): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addBatch(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addBatch(arg0);
            return result;
        }
    }
    async addClassContent(arg0: ClassContent): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addClassContent(to_candid_ClassContent_n8(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addClassContent(to_candid_ClassContent_n8(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async addFaculty(arg0: Faculty): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addFaculty(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addFaculty(arg0);
            return result;
        }
    }
    async addGalleryItem(arg0: GalleryItem): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addGalleryItem(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addGalleryItem(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n14(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n14(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async deleteBatch(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteBatch(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteBatch(arg0);
            return result;
        }
    }
    async deleteClassContent(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteClassContent(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteClassContent(arg0);
            return result;
        }
    }
    async deleteFaculty(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteFaculty(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteFaculty(arg0);
            return result;
        }
    }
    async deleteGalleryItem(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteGalleryItem(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteGalleryItem(arg0);
            return result;
        }
    }
    async getActiveBatches(): Promise<Array<Batch>> {
        if (this.processError) {
            try {
                const result = await this.actor.getActiveBatches();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getActiveBatches();
            return result;
        }
    }
    async getAllAdmissionInquiries(): Promise<Array<AdmissionInquiry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllAdmissionInquiries();
                return from_candid_vec_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllAdmissionInquiries();
            return from_candid_vec_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllBatches(): Promise<Array<Batch>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllBatches();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllBatches();
            return result;
        }
    }
    async getAllFaculty(): Promise<Array<Faculty>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllFaculty();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllFaculty();
            return result;
        }
    }
    async getAllGalleryItems(): Promise<Array<GalleryItem>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllGalleryItems();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllGalleryItems();
            return result;
        }
    }
    async getByClass(arg0: ClassLevel): Promise<Array<ClassContent>> {
        if (this.processError) {
            try {
                const result = await this.actor.getByClass(to_candid_ClassLevel_n12(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getByClass(to_candid_ClassLevel_n12(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async getByClassAndType(arg0: ClassLevel, arg1: ContentType): Promise<Array<ClassContent>> {
        if (this.processError) {
            try {
                const result = await this.actor.getByClassAndType(to_candid_ClassLevel_n12(this._uploadFile, this._downloadFile, arg0), to_candid_ContentType_n10(this._uploadFile, this._downloadFile, arg1));
                return from_candid_vec_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getByClassAndType(to_candid_ClassLevel_n12(this._uploadFile, this._downloadFile, arg0), to_candid_ContentType_n10(this._uploadFile, this._downloadFile, arg1));
            return from_candid_vec_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n26(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n26(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n27(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n27(this._uploadFile, this._downloadFile, result);
        }
    }
    async getStats(): Promise<Stats> {
        if (this.processError) {
            try {
                const result = await this.actor.getStats();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStats();
            return result;
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n26(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n26(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async markInquiryAsRead(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.markInquiryAsRead(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.markInquiryAsRead(arg0);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async submitAdmissionInquiry(arg0: AdmissionInquiry): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.submitAdmissionInquiry(to_candid_AdmissionInquiry_n29(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitAdmissionInquiry(to_candid_AdmissionInquiry_n29(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async updateBatch(arg0: string, arg1: Batch): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateBatch(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateBatch(arg0, arg1);
            return result;
        }
    }
    async updateClassContent(arg0: string, arg1: ClassContent): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateClassContent(arg0, to_candid_ClassContent_n8(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateClassContent(arg0, to_candid_ClassContent_n8(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async updateFaculty(arg0: string, arg1: Faculty): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateFaculty(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateFaculty(arg0, arg1);
            return result;
        }
    }
}
function from_candid_AdmissionInquiry_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AdmissionInquiry): AdmissionInquiry {
    return from_candid_record_n18(_uploadFile, _downloadFile, value);
}
function from_candid_ClassContent_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ClassContent): ClassContent {
    return from_candid_record_n23(_uploadFile, _downloadFile, value);
}
function from_candid_ClassLevel_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ClassLevel): ClassLevel {
    return from_candid_variant_n20(_uploadFile, _downloadFile, value);
}
function from_candid_ContentType_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ContentType): ContentType {
    return from_candid_variant_n25(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n28(_uploadFile, _downloadFile, value);
}
function from_candid__CaffeineStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __CaffeineStorageRefillResult): _CaffeineStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    name: string;
    createdAt: bigint;
    isRead: boolean;
    email: string;
    message: string;
    classLevel: _ClassLevel;
    mobile: string;
}): {
    id: string;
    name: string;
    createdAt: bigint;
    isRead: boolean;
    email: string;
    message: string;
    classLevel: ClassLevel;
    mobile: string;
} {
    return {
        id: value.id,
        name: value.name,
        createdAt: value.createdAt,
        isRead: value.isRead,
        email: value.email,
        message: value.message,
        classLevel: from_candid_ClassLevel_n19(_uploadFile, _downloadFile, value.classLevel),
        mobile: value.mobile
    };
}
function from_candid_record_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    url: string;
    title: string;
    contentType: _ContentType;
    body: string;
    createdAt: bigint;
    description: string;
    classLevel: _ClassLevel;
}): {
    id: string;
    url: string;
    title: string;
    contentType: ContentType;
    body: string;
    createdAt: bigint;
    description: string;
    classLevel: ClassLevel;
} {
    return {
        id: value.id,
        url: value.url,
        title: value.title,
        contentType: from_candid_ContentType_n24(_uploadFile, _downloadFile, value.contentType),
        body: value.body,
        createdAt: value.createdAt,
        description: value.description,
        classLevel: from_candid_ClassLevel_n19(_uploadFile, _downloadFile, value.classLevel)
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_variant_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Class1: null;
} | {
    Class2: null;
} | {
    Class3: null;
} | {
    Class4: null;
} | {
    Class5: null;
} | {
    Class6: null;
} | {
    Class7: null;
} | {
    Class8: null;
} | {
    Nursery: null;
}): ClassLevel {
    return "Class1" in value ? ClassLevel.Class1 : "Class2" in value ? ClassLevel.Class2 : "Class3" in value ? ClassLevel.Class3 : "Class4" in value ? ClassLevel.Class4 : "Class5" in value ? ClassLevel.Class5 : "Class6" in value ? ClassLevel.Class6 : "Class7" in value ? ClassLevel.Class7 : "Class8" in value ? ClassLevel.Class8 : "Nursery" in value ? ClassLevel.Nursery : value;
}
function from_candid_variant_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pdf: null;
} | {
    video: null;
} | {
    test: null;
} | {
    message: null;
} | {
    worksheet: null;
}): ContentType {
    return "pdf" in value ? ContentType.pdf : "video" in value ? ContentType.video : "test" in value ? ContentType.test : "message" in value ? ContentType.message : "worksheet" in value ? ContentType.worksheet : value;
}
function from_candid_variant_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_vec_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_AdmissionInquiry>): Array<AdmissionInquiry> {
    return value.map((x)=>from_candid_AdmissionInquiry_n17(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ClassContent>): Array<ClassContent> {
    return value.map((x)=>from_candid_ClassContent_n22(_uploadFile, _downloadFile, x));
}
function to_candid_AdmissionInquiry_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AdmissionInquiry): _AdmissionInquiry {
    return to_candid_record_n30(_uploadFile, _downloadFile, value);
}
function to_candid_ClassContent_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ClassContent): _ClassContent {
    return to_candid_record_n9(_uploadFile, _downloadFile, value);
}
function to_candid_ClassLevel_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ClassLevel): _ClassLevel {
    return to_candid_variant_n13(_uploadFile, _downloadFile, value);
}
function to_candid_ContentType_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ContentType): _ContentType {
    return to_candid_variant_n11(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n15(_uploadFile, _downloadFile, value);
}
function to_candid__CaffeineStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation): __CaffeineStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation | null): [] | [__CaffeineStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__CaffeineStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
function to_candid_record_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    name: string;
    createdAt: bigint;
    isRead: boolean;
    email: string;
    message: string;
    classLevel: ClassLevel;
    mobile: string;
}): {
    id: string;
    name: string;
    createdAt: bigint;
    isRead: boolean;
    email: string;
    message: string;
    classLevel: _ClassLevel;
    mobile: string;
} {
    return {
        id: value.id,
        name: value.name,
        createdAt: value.createdAt,
        isRead: value.isRead,
        email: value.email,
        message: value.message,
        classLevel: to_candid_ClassLevel_n12(_uploadFile, _downloadFile, value.classLevel),
        mobile: value.mobile
    };
}
function to_candid_record_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    url: string;
    title: string;
    contentType: ContentType;
    body: string;
    createdAt: bigint;
    description: string;
    classLevel: ClassLevel;
}): {
    id: string;
    url: string;
    title: string;
    contentType: _ContentType;
    body: string;
    createdAt: bigint;
    description: string;
    classLevel: _ClassLevel;
} {
    return {
        id: value.id,
        url: value.url,
        title: value.title,
        contentType: to_candid_ContentType_n10(_uploadFile, _downloadFile, value.contentType),
        body: value.body,
        createdAt: value.createdAt,
        description: value.description,
        classLevel: to_candid_ClassLevel_n12(_uploadFile, _downloadFile, value.classLevel)
    };
}
function to_candid_variant_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ContentType): {
    pdf: null;
} | {
    video: null;
} | {
    test: null;
} | {
    message: null;
} | {
    worksheet: null;
} {
    return value == ContentType.pdf ? {
        pdf: null
    } : value == ContentType.video ? {
        video: null
    } : value == ContentType.test ? {
        test: null
    } : value == ContentType.message ? {
        message: null
    } : value == ContentType.worksheet ? {
        worksheet: null
    } : value;
}
function to_candid_variant_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ClassLevel): {
    Class1: null;
} | {
    Class2: null;
} | {
    Class3: null;
} | {
    Class4: null;
} | {
    Class5: null;
} | {
    Class6: null;
} | {
    Class7: null;
} | {
    Class8: null;
} | {
    Nursery: null;
} {
    return value == ClassLevel.Class1 ? {
        Class1: null
    } : value == ClassLevel.Class2 ? {
        Class2: null
    } : value == ClassLevel.Class3 ? {
        Class3: null
    } : value == ClassLevel.Class4 ? {
        Class4: null
    } : value == ClassLevel.Class5 ? {
        Class5: null
    } : value == ClassLevel.Class6 ? {
        Class6: null
    } : value == ClassLevel.Class7 ? {
        Class7: null
    } : value == ClassLevel.Class8 ? {
        Class8: null
    } : value == ClassLevel.Nursery ? {
        Nursery: null
    } : value;
}
function to_candid_variant_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
